#!/bin/bash
clear
dnf install -y dist/vipnetclient-gui_*.rpm
chmod +x dist/vipnet_dns.sh
echo "[global]
; Path where to install keys
;config_dir=
; Path where to store log files. By default <config_dir>/var/log
;log_dir=

[dns]
; User defined trusted DNS servers, separated by comma
trusted=10.14.100.222,10.17.101.222
; Using iptables rules for DNS requests redirection to ViPNet
; If iptables not enabled (=off) then IP 11.254.254.254 will be used as ViPNet DNS server
;     and this IP must be added manually to required configs
;iptables=off" > /etc/vipnet.conf

echo "# Generated by authselect on Wed Jul 27 15:07:28 2022
# Do not modify this file manually.

# If you want to make changes to nsswitch.conf please modify
# /etc/authselect/user-nsswitch.conf and run 'authselect apply-changes'.
#
# Note that your changes may not be applied as they may be
# overwritten by selected profile. Maps set in the authselect
# profile takes always precedence and overwrites the same maps
# set in the user file. Only maps that are not set by the profile
# are applied from the user file.
#
# For example, if the profile sets:
#     passwd: sss files
# and /etc/authselect/user-nsswitch.conf contains:
#     passwd: files
#     hosts: files dns
# the resulting generated nsswitch.conf will be:
#     passwd: sss files # from profile
#     hosts: files dns  # from user file

passwd:     sss files systemd
group:      sss files systemd
netgroup:   sss files
automount:  sss files
services:   sss files

# Included from /etc/authselect/user-nsswitch.conf

#
# /etc/nsswitch.conf
#
# An example Name Service Switch config file. This file should be
# sorted with the most-used services at the beginning.
#
# The entry '[NOTFOUND=return]' means that the search for an
# entry should stop if the search in the previous entry turned
# up nothing. Note that if the search failed due to some other reason
# (like no NIS server responding) then the search continues with the
# next entry.
#
# Valid entries include:
#
#	nisplus			Use NIS+ (NIS version 3)
#	nis			Use NIS (NIS version 2), also called YP
#	dns			Use DNS (Domain Name Service)
#	files			Use the local files in /etc
#	db			Use the pre-processed /var/db files
#	compat			Use /etc files plus *_compat pseudo-databases
#	hesiod			Use Hesiod (DNS) for user lookups
#	sss			Use sssd (System Security Services Daemon)
#	[NOTFOUND=return]	Stop searching if not found so far
#
# 'sssd' performs its own 'files'-based caching, so it should
# generally come before 'files'.

# To use 'db', install the nss_db package, and put the 'db' in front
# of 'files' for entries you want to be looked up first in the
# databases, like this:
#
# passwd:    db files
# shadow:    db files
# group:     db files

shadow:     files sss

hosts:      files resolve [!UNAVAIL=return] myhostname dns

# mdns4_minimal [NOTFOUND=return] dns

bootparams: files

ethers:     files
netmasks:   files
networks:   files
protocols:  files
rpc:        files


publickey:  files

aliases:    files" > /etc/authselect/nsswitch.conf

authselect apply-changes

echo "Скрипт выполнен"

touch /home/logvipnet.txt
cat /etc/vipnet.conf >> logvipnet.txt
echo "_________________nsswitch.conf_________________" >> logvipnet.txt
cat /etc/authselect/nsswitch.conf >> logvipnet.txt
echo "Создан лог файл logvipnet.txt в /home/"
cat /etc/vipnet.conf
cat /etc/authselect/nsswitch.conf
